apiVersion: v1
kind: Service
metadata:
  name: clus2017iosxedemo
  namespace: hapresto
  labels:
    app: clus2017iosxedemo
    tier: web
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: clus2017iosxedemo
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clus2017iosxedemo-ingress
  namespace: hapresto
  annotations:
    kubernetes.io/ingress.class: "gce"
    dns.alpha.kubernetes.io/external: "true"
spec:
  rules:
  - host: ios-xe-demo.ciscodevnetcloud.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: clus2017iosxedemo
          servicePort: 80
      - path: /static/*
        backend:
          serviceName: clus2017iosxedemo
          servicePort: 80
      - path: /templates/*
        backend:
          serviceName: clus2017iosxedemo
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clus2017iosxedemo
  namespace: hapresto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clus2017iosxedemo
        tier: web
    spec:
      containers:
      - name: clus2017iosxedemo
        image: hpreston/clus2017_iosxe_demo_portal:latest
        env:
        - name: CLUSTER_MASTERURL
          value: https://kubernetes.default.svc.cluster.local
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 100M
      restartPolicy: Always